/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as CheckoutLayoutRouteImport } from './pages/checkout/layout'
import { Route as AppLayoutRouteImport } from './pages/app/layout'
import { Route as AdminLayoutRouteImport } from './pages/admin/layout'
import { Route as AuthLayoutRouteImport } from './pages/_auth/layout'
import { Route as SlugLayoutRouteImport } from './pages/$slug/layout'
import { Route as CheckoutIndexRouteImport } from './pages/checkout/index'
import { Route as AppIndexRouteImport } from './pages/app/index'
import { Route as AdminIndexRouteImport } from './pages/admin/index'
import { Route as MarketingIndexRouteImport } from './pages/_marketing/index'
import { Route as SlugIndexRouteImport } from './pages/$slug/index'
import { Route as CheckoutSuccessRouteImport } from './pages/checkout/success'
import { Route as CheckoutCancelRouteImport } from './pages/checkout/cancel'
import { Route as AuthRegisterRouteImport } from './pages/_auth/register'
import { Route as AuthPreRegisterRouteImport } from './pages/_auth/pre-register'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AppStoreIndexRouteImport } from './pages/app/store/index'
import { Route as AppServicesIndexRouteImport } from './pages/app/services/index'
import { Route as AppPackagesIndexRouteImport } from './pages/app/packages/index'
import { Route as AppLoyaltyProgramsIndexRouteImport } from './pages/app/loyalty-programs/index'
import { Route as AppEmployeesIndexRouteImport } from './pages/app/employees/index'
import { Route as AppDashboardIndexRouteImport } from './pages/app/dashboard/index'
import { Route as AppCustomersIndexRouteImport } from './pages/app/customers/index'
import { Route as AppCategoriesIndexRouteImport } from './pages/app/categories/index'
import { Route as SlugSchedulingIndexRouteImport } from './pages/$slug/scheduling/index'
import { Route as AdminPublicLoginRouteImport } from './pages/admin/_public/login'
import { Route as AppServicesNewIndexRouteImport } from './pages/app/services/new/index'
import { Route as AppServicesServiceIdIndexRouteImport } from './pages/app/services/$serviceId/index'
import { Route as AppPackagesNewIndexRouteImport } from './pages/app/packages/new/index'
import { Route as AppPackagesPackageIdIndexRouteImport } from './pages/app/packages/$packageId/index'
import { Route as AppLoyaltyProgramsNewIndexRouteImport } from './pages/app/loyalty-programs/new/index'
import { Route as AppLoyaltyProgramsProgramIdIndexRouteImport } from './pages/app/loyalty-programs/$programId/index'
import { Route as AppEmployeesNewIndexRouteImport } from './pages/app/employees/new/index'
import { Route as AppEmployeesEmployeeIdIndexRouteImport } from './pages/app/employees/$employeeId/index'
import { Route as AppCustomersNewIndexRouteImport } from './pages/app/customers/new/index'
import { Route as AppCustomersCustomerIdIndexRouteImport } from './pages/app/customers/$customerId/index'

const CheckoutLayoutRoute = CheckoutLayoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugLayoutRoute = SlugLayoutRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutLayoutRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/_marketing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugLayoutRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutLayoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthPreRegisterRoute = AuthPreRegisterRouteImport.update({
  id: '/pre-register',
  path: '/pre-register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppStoreIndexRoute = AppStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPackagesIndexRoute = AppPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLoyaltyProgramsIndexRoute = AppLoyaltyProgramsIndexRouteImport.update({
  id: '/loyalty-programs/',
  path: '/loyalty-programs/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const SlugSchedulingIndexRoute = SlugSchedulingIndexRouteImport.update({
  id: '/scheduling/',
  path: '/scheduling/',
  getParentRoute: () => SlugLayoutRoute,
} as any)
const AdminPublicLoginRoute = AdminPublicLoginRouteImport.update({
  id: '/_public/login',
  path: '/login',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AppServicesNewIndexRoute = AppServicesNewIndexRouteImport.update({
  id: '/services/new/',
  path: '/services/new/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppServicesServiceIdIndexRoute =
  AppServicesServiceIdIndexRouteImport.update({
    id: '/services/$serviceId/',
    path: '/services/$serviceId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppPackagesNewIndexRoute = AppPackagesNewIndexRouteImport.update({
  id: '/packages/new/',
  path: '/packages/new/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPackagesPackageIdIndexRoute =
  AppPackagesPackageIdIndexRouteImport.update({
    id: '/packages/$packageId/',
    path: '/packages/$packageId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLoyaltyProgramsNewIndexRoute =
  AppLoyaltyProgramsNewIndexRouteImport.update({
    id: '/loyalty-programs/new/',
    path: '/loyalty-programs/new/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLoyaltyProgramsProgramIdIndexRoute =
  AppLoyaltyProgramsProgramIdIndexRouteImport.update({
    id: '/loyalty-programs/$programId/',
    path: '/loyalty-programs/$programId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppEmployeesNewIndexRoute = AppEmployeesNewIndexRouteImport.update({
  id: '/employees/new/',
  path: '/employees/new/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppEmployeesEmployeeIdIndexRoute =
  AppEmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppCustomersNewIndexRoute = AppCustomersNewIndexRouteImport.update({
  id: '/customers/new/',
  path: '/customers/new/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCustomersCustomerIdIndexRoute =
  AppCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugLayoutRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/app': typeof AppLayoutRouteWithChildren
  '/checkout': typeof CheckoutLayoutRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/pre-register': typeof AuthPreRegisterRoute
  '/register': typeof AuthRegisterRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/$slug/': typeof SlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/admin/login': typeof AdminPublicLoginRoute
  '/$slug/scheduling/': typeof SlugSchedulingIndexRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/loyalty-programs/': typeof AppLoyaltyProgramsIndexRoute
  '/app/packages/': typeof AppPackagesIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/store/': typeof AppStoreIndexRoute
  '/app/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/app/customers/new/': typeof AppCustomersNewIndexRoute
  '/app/employees/$employeeId/': typeof AppEmployeesEmployeeIdIndexRoute
  '/app/employees/new/': typeof AppEmployeesNewIndexRoute
  '/app/loyalty-programs/$programId/': typeof AppLoyaltyProgramsProgramIdIndexRoute
  '/app/loyalty-programs/new/': typeof AppLoyaltyProgramsNewIndexRoute
  '/app/packages/$packageId/': typeof AppPackagesPackageIdIndexRoute
  '/app/packages/new/': typeof AppPackagesNewIndexRoute
  '/app/services/$serviceId/': typeof AppServicesServiceIdIndexRoute
  '/app/services/new/': typeof AppServicesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/login': typeof AuthLoginRoute
  '/pre-register': typeof AuthPreRegisterRoute
  '/register': typeof AuthRegisterRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/$slug': typeof SlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/admin/login': typeof AdminPublicLoginRoute
  '/$slug/scheduling': typeof SlugSchedulingIndexRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/employees': typeof AppEmployeesIndexRoute
  '/app/loyalty-programs': typeof AppLoyaltyProgramsIndexRoute
  '/app/packages': typeof AppPackagesIndexRoute
  '/app/services': typeof AppServicesIndexRoute
  '/app/store': typeof AppStoreIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdIndexRoute
  '/app/customers/new': typeof AppCustomersNewIndexRoute
  '/app/employees/$employeeId': typeof AppEmployeesEmployeeIdIndexRoute
  '/app/employees/new': typeof AppEmployeesNewIndexRoute
  '/app/loyalty-programs/$programId': typeof AppLoyaltyProgramsProgramIdIndexRoute
  '/app/loyalty-programs/new': typeof AppLoyaltyProgramsNewIndexRoute
  '/app/packages/$packageId': typeof AppPackagesPackageIdIndexRoute
  '/app/packages/new': typeof AppPackagesNewIndexRoute
  '/app/services/$serviceId': typeof AppServicesServiceIdIndexRoute
  '/app/services/new': typeof AppServicesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugLayoutRouteWithChildren
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/app': typeof AppLayoutRouteWithChildren
  '/checkout': typeof CheckoutLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/pre-register': typeof AuthPreRegisterRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/$slug/': typeof SlugIndexRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/admin/_public/login': typeof AdminPublicLoginRoute
  '/$slug/scheduling/': typeof SlugSchedulingIndexRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/loyalty-programs/': typeof AppLoyaltyProgramsIndexRoute
  '/app/packages/': typeof AppPackagesIndexRoute
  '/app/services/': typeof AppServicesIndexRoute
  '/app/store/': typeof AppStoreIndexRoute
  '/app/customers/$customerId/': typeof AppCustomersCustomerIdIndexRoute
  '/app/customers/new/': typeof AppCustomersNewIndexRoute
  '/app/employees/$employeeId/': typeof AppEmployeesEmployeeIdIndexRoute
  '/app/employees/new/': typeof AppEmployeesNewIndexRoute
  '/app/loyalty-programs/$programId/': typeof AppLoyaltyProgramsProgramIdIndexRoute
  '/app/loyalty-programs/new/': typeof AppLoyaltyProgramsNewIndexRoute
  '/app/packages/$packageId/': typeof AppPackagesPackageIdIndexRoute
  '/app/packages/new/': typeof AppPackagesNewIndexRoute
  '/app/services/$serviceId/': typeof AppServicesServiceIdIndexRoute
  '/app/services/new/': typeof AppServicesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/login'
    | '/pre-register'
    | '/register'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/$slug/'
    | '/admin/'
    | '/app/'
    | '/checkout/'
    | '/admin/login'
    | '/$slug/scheduling/'
    | '/app/categories/'
    | '/app/customers/'
    | '/app/dashboard/'
    | '/app/employees/'
    | '/app/loyalty-programs/'
    | '/app/packages/'
    | '/app/services/'
    | '/app/store/'
    | '/app/customers/$customerId/'
    | '/app/customers/new/'
    | '/app/employees/$employeeId/'
    | '/app/employees/new/'
    | '/app/loyalty-programs/$programId/'
    | '/app/loyalty-programs/new/'
    | '/app/packages/$packageId/'
    | '/app/packages/new/'
    | '/app/services/$serviceId/'
    | '/app/services/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pre-register'
    | '/register'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/$slug'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/admin/login'
    | '/$slug/scheduling'
    | '/app/categories'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/employees'
    | '/app/loyalty-programs'
    | '/app/packages'
    | '/app/services'
    | '/app/store'
    | '/app/customers/$customerId'
    | '/app/customers/new'
    | '/app/employees/$employeeId'
    | '/app/employees/new'
    | '/app/loyalty-programs/$programId'
    | '/app/loyalty-programs/new'
    | '/app/packages/$packageId'
    | '/app/packages/new'
    | '/app/services/$serviceId'
    | '/app/services/new'
  id:
    | '__root__'
    | '/$slug'
    | '/_auth'
    | '/admin'
    | '/app'
    | '/checkout'
    | '/_auth/login'
    | '/_auth/pre-register'
    | '/_auth/register'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/$slug/'
    | '/_marketing/'
    | '/admin/'
    | '/app/'
    | '/checkout/'
    | '/admin/_public/login'
    | '/$slug/scheduling/'
    | '/app/categories/'
    | '/app/customers/'
    | '/app/dashboard/'
    | '/app/employees/'
    | '/app/loyalty-programs/'
    | '/app/packages/'
    | '/app/services/'
    | '/app/store/'
    | '/app/customers/$customerId/'
    | '/app/customers/new/'
    | '/app/employees/$employeeId/'
    | '/app/employees/new/'
    | '/app/loyalty-programs/$programId/'
    | '/app/loyalty-programs/new/'
    | '/app/packages/$packageId/'
    | '/app/packages/new/'
    | '/app/services/$serviceId/'
    | '/app/services/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugLayoutRoute: typeof SlugLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  CheckoutLayoutRoute: typeof CheckoutLayoutRouteWithChildren
  MarketingIndexRoute: typeof MarketingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutLayoutRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugLayoutRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutLayoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutLayoutRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/pre-register': {
      id: '/_auth/pre-register'
      path: '/pre-register'
      fullPath: '/pre-register'
      preLoaderRoute: typeof AuthPreRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/app/store/': {
      id: '/app/store/'
      path: '/store'
      fullPath: '/app/store/'
      preLoaderRoute: typeof AppStoreIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/services/': {
      id: '/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/packages/': {
      id: '/app/packages/'
      path: '/packages'
      fullPath: '/app/packages/'
      preLoaderRoute: typeof AppPackagesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/loyalty-programs/': {
      id: '/app/loyalty-programs/'
      path: '/loyalty-programs'
      fullPath: '/app/loyalty-programs/'
      preLoaderRoute: typeof AppLoyaltyProgramsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/employees/': {
      id: '/app/employees/'
      path: '/employees'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/categories/': {
      id: '/app/categories/'
      path: '/categories'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/$slug/scheduling/': {
      id: '/$slug/scheduling/'
      path: '/scheduling'
      fullPath: '/$slug/scheduling/'
      preLoaderRoute: typeof SlugSchedulingIndexRouteImport
      parentRoute: typeof SlugLayoutRoute
    }
    '/admin/_public/login': {
      id: '/admin/_public/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminPublicLoginRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/app/services/new/': {
      id: '/app/services/new/'
      path: '/services/new'
      fullPath: '/app/services/new/'
      preLoaderRoute: typeof AppServicesNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/services/$serviceId/': {
      id: '/app/services/$serviceId/'
      path: '/services/$serviceId'
      fullPath: '/app/services/$serviceId/'
      preLoaderRoute: typeof AppServicesServiceIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/packages/new/': {
      id: '/app/packages/new/'
      path: '/packages/new'
      fullPath: '/app/packages/new/'
      preLoaderRoute: typeof AppPackagesNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/packages/$packageId/': {
      id: '/app/packages/$packageId/'
      path: '/packages/$packageId'
      fullPath: '/app/packages/$packageId/'
      preLoaderRoute: typeof AppPackagesPackageIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/loyalty-programs/new/': {
      id: '/app/loyalty-programs/new/'
      path: '/loyalty-programs/new'
      fullPath: '/app/loyalty-programs/new/'
      preLoaderRoute: typeof AppLoyaltyProgramsNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/loyalty-programs/$programId/': {
      id: '/app/loyalty-programs/$programId/'
      path: '/loyalty-programs/$programId'
      fullPath: '/app/loyalty-programs/$programId/'
      preLoaderRoute: typeof AppLoyaltyProgramsProgramIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/employees/new/': {
      id: '/app/employees/new/'
      path: '/employees/new'
      fullPath: '/app/employees/new/'
      preLoaderRoute: typeof AppEmployeesNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/employees/$employeeId/': {
      id: '/app/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/app/employees/$employeeId/'
      preLoaderRoute: typeof AppEmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/customers/new/': {
      id: '/app/customers/new/'
      path: '/customers/new'
      fullPath: '/app/customers/new/'
      preLoaderRoute: typeof AppCustomersNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/customers/$customerId/': {
      id: '/app/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId/'
      preLoaderRoute: typeof AppCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface SlugLayoutRouteChildren {
  SlugIndexRoute: typeof SlugIndexRoute
  SlugSchedulingIndexRoute: typeof SlugSchedulingIndexRoute
}

const SlugLayoutRouteChildren: SlugLayoutRouteChildren = {
  SlugIndexRoute: SlugIndexRoute,
  SlugSchedulingIndexRoute: SlugSchedulingIndexRoute,
}

const SlugLayoutRouteWithChildren = SlugLayoutRoute._addFileChildren(
  SlugLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPreRegisterRoute: typeof AuthPreRegisterRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthPreRegisterRoute: AuthPreRegisterRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPublicLoginRoute: typeof AdminPublicLoginRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPublicLoginRoute: AdminPublicLoginRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppLoyaltyProgramsIndexRoute: typeof AppLoyaltyProgramsIndexRoute
  AppPackagesIndexRoute: typeof AppPackagesIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppStoreIndexRoute: typeof AppStoreIndexRoute
  AppCustomersCustomerIdIndexRoute: typeof AppCustomersCustomerIdIndexRoute
  AppCustomersNewIndexRoute: typeof AppCustomersNewIndexRoute
  AppEmployeesEmployeeIdIndexRoute: typeof AppEmployeesEmployeeIdIndexRoute
  AppEmployeesNewIndexRoute: typeof AppEmployeesNewIndexRoute
  AppLoyaltyProgramsProgramIdIndexRoute: typeof AppLoyaltyProgramsProgramIdIndexRoute
  AppLoyaltyProgramsNewIndexRoute: typeof AppLoyaltyProgramsNewIndexRoute
  AppPackagesPackageIdIndexRoute: typeof AppPackagesPackageIdIndexRoute
  AppPackagesNewIndexRoute: typeof AppPackagesNewIndexRoute
  AppServicesServiceIdIndexRoute: typeof AppServicesServiceIdIndexRoute
  AppServicesNewIndexRoute: typeof AppServicesNewIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppLoyaltyProgramsIndexRoute: AppLoyaltyProgramsIndexRoute,
  AppPackagesIndexRoute: AppPackagesIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppStoreIndexRoute: AppStoreIndexRoute,
  AppCustomersCustomerIdIndexRoute: AppCustomersCustomerIdIndexRoute,
  AppCustomersNewIndexRoute: AppCustomersNewIndexRoute,
  AppEmployeesEmployeeIdIndexRoute: AppEmployeesEmployeeIdIndexRoute,
  AppEmployeesNewIndexRoute: AppEmployeesNewIndexRoute,
  AppLoyaltyProgramsProgramIdIndexRoute: AppLoyaltyProgramsProgramIdIndexRoute,
  AppLoyaltyProgramsNewIndexRoute: AppLoyaltyProgramsNewIndexRoute,
  AppPackagesPackageIdIndexRoute: AppPackagesPackageIdIndexRoute,
  AppPackagesNewIndexRoute: AppPackagesNewIndexRoute,
  AppServicesServiceIdIndexRoute: AppServicesServiceIdIndexRoute,
  AppServicesNewIndexRoute: AppServicesNewIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface CheckoutLayoutRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

const CheckoutLayoutRouteChildren: CheckoutLayoutRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}

const CheckoutLayoutRouteWithChildren = CheckoutLayoutRoute._addFileChildren(
  CheckoutLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SlugLayoutRoute: SlugLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AppLayoutRoute: AppLayoutRouteWithChildren,
  CheckoutLayoutRoute: CheckoutLayoutRouteWithChildren,
  MarketingIndexRoute: MarketingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
